### Test GET "/" Website
GET http://localhost:5758

### Test GET "/dashboard" Website
GET http://localhost:5758/dashboard

### Test Data Endpoint
GET http://localhost:5758/api/data

### Create Data Endpoint (POST)
POST http://localhost:5758/api/data
Content-Type: application/json

{
  "name":"budi-json"
}

